### ISSUE TITLE
Firefox Flickering

### ISSUE THREAD

**Issue by bahamagician** [creativeaura/threesixty-slider#75]
I have a slider that plays automatically.  However, on Firefox, during the first loop through the slider, the images flicker quite a bit.  It even happens on the Custom Controls page on the demo site.  If you visit that page in Firefox and hit the play button, you'll notice that the images flicker during the first run through:

http://www.360slider.com/custom_controls.html

Any ideas what I can do to fix this?

**Comment by Igloczek** [comment]
Just remove width change in CSS files
```css
.threesixty .threesixty_images img.previous-image {
  visibility: hidden;
}
.threesixty .threesixty_images img.current-image {
  visibility: visible;
}
```
